# Generated by Django 2.1.3 on 2018-11-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='arm_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bridge_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_width',
        ),
    ]
