# Generated by Django 2.1.3 on 2018-11-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFeatures',
            new_name='Features',
        ),
        migrations.RenameModel(
            old_name='ProductSpecs',
            new_name='Specs',
        ),
    ]
