# Generated by Django 2.1.3 on 2018-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181116_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arm_length',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bridge_length',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lens_height',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lens_width',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
