# Generated by Django 2.1.3 on 2018-12-01 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_detail_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_photo', models.CharField(default='/', max_length=75)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
